// Pure schema->TS emitter: data in, `declare module "zpi-sdk"` string out.
// No fetch, no fs, no node builtins — keeps every mapping rule unit-testable.
import type { EndpointSchema, SchemaField } from "../resources/catalog";

export interface EmitEndpoint {
	slug: string;
	schema: EndpointSchema;
}

export interface EmitScraper {
	category: string;
	scraper: string;
	endpoints: EmitEndpoint[];
}

// Render a single enum member per its JS type (string->quoted, number->bare).
function literal(value: unknown): string {
	return typeof value === "number" ? String(value) : JSON.stringify(value);
}

export function mapFieldType(field: SchemaField): string {
	if (Array.isArray(field.enumValues) && field.enumValues.length > 0) {
		return field.enumValues.map(literal).join(" | ");
	}
	switch (String(field.type).toLowerCase()) {
		case "string":
		case "url":
			return "string";
		case "number":
		case "integer":
		case "float":
			return "number";
		case "boolean":
		case "bool":
			return "boolean";
		case "array":
			return "unknown[]";
		case "object":
			return "Record<string, unknown>";
		default:
			return "unknown";
	}
}

// Quote keys that aren't valid TS identifiers (hyphenated slugs, dots, …).
function propKey(name: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

// `*/` inside a description would terminate the JSDoc block early.
function docComment(description: string): string {
	return `/** ${description.replace(/\*\//g, "*\\/")} */ `;
}

export function emitParams(fields: SchemaField[]): string {
	if (!fields || fields.length === 0) return "Record<string, unknown>";
	const props = fields.map((f) => {
		const doc = f.description ? docComment(f.description) : "";
		const opt = f.required ? "" : "?";
		return `${doc}${propKey(f.name)}${opt}: ${mapFieldType(f)};`;
	});
	return `{ ${props.join(" ")} }`;
}

export function emitScraperMap(
	scrapers: EmitScraper[],
	opts: { baseURL: string }
): string {
	// Deterministic ordering keeps re-runs diff-stable for drift detection.
	const sorted = [...scrapers].sort((a, b) =>
		`${a.category}:${a.scraper}`.localeCompare(`${b.category}:${b.scraper}`)
	);
	const lines: string[] = [];
	lines.push("// GENERATED by zpi codegen — do not edit.");
	lines.push(`// source: ${opts.baseURL}`);
	lines.push("// regenerate with: npx zpi codegen");
	lines.push("");
	// Without a top-level export the file is an ambient module DECLARATION that
	// shadows the real package types; `export {}` makes it an augmentation.
	lines.push("export {};");
	lines.push("");
	lines.push('declare module "zpi-sdk" {');
	lines.push("\tinterface ScraperMap {");
	for (const s of sorted) {
		const eps = [...s.endpoints].sort((a, b) =>
			a.slug.localeCompare(b.slug)
		);
		const entries = eps.map(
			(ep) =>
				`${propKey(ep.slug)}: { params: ${emitParams(ep.schema.fields)}; result: unknown };`
		);
		lines.push(
			`\t\t"${s.category}:${s.scraper}": { ${entries.join(" ")} };`
		);
	}
	lines.push("\t}");
	lines.push("}");
	lines.push("");
	return lines.join("\n");
}
